proxy: # see https://www.shinyproxy.io/configuration/ for options
  port: 8080
  container-wait-time: 20000
  landing-page: /app/workHORSE
  authentication: none
  hide-navbar: true
  docker:
    internal-networking: true
  specs:
  - id: workHORSE
    display-name: workHORSE
    description: workHORSE app
    container-image: chriskypri/workhorse-app:stable
    container-network: sp-workhorse-net
    container-volumes: ["/mnt/storage_fast/synthpop:/mnt/storage_fast/synthpop"]
    port: 9898
server:
  servlet.session.timeout: 36000
logging:
  file:
    shinyproxy.log
